version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "mysql -uroot -pmysecretpassword -e 'select 1;'"
      interval: 1s
      retries: 20
  app:
    build:
      context: .
      dockerfile: workflow_viewer/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://root:mysecretpassword@db:3306/machina_labs"
    depends_on:
      db:
        condition: service_healthy
